# Generated by Django 4.2.6 on 2023-11-23 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Staff', 'Staff'), ('Manager', 'Manager'), ('Administrator', 'Administrator')], default='Staff', max_length=100)),
                ('region', models.CharField(choices=[('Flacq', 'Flacq'), ('Grand Port', 'Grand Port'), ('Moka', 'Moka'), ('Pamplemousses', 'Pamplemousses'), ('Plaines Wilhems', 'Plaines Wilhems'), ('Port Louis', 'Port Louis'), ('Rivière du Rempart', 'Rivière du Rempart'), ('Rivière Noire', 'Rivière Noire'), ('Savanne', 'Savanne'), ('Rodrigues', 'Rodrigues')], default='Plaines Wilhems', max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
