# Generated by Django 5.0.3 on 2024-03-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='business',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
