# Generated by Django 5.0.3 on 2024-03-23 02:27

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='users.Business'),  # Changed 'business' to 'Business'
        ),
    ]
