# Generated by Django 5.0.3 on 2024-03-23 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_business_alter_role_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='business',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
    ]
