# Generated by Django 5.0.3 on 2024-03-25 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
        ('users', '0004_remove_role_business_userprofile_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_config.business'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
