# Generated by Django 5.0.3 on 2024-03-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0002_business_address_business_brn_business_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.AlterField(
            model_name='business',
            name='brn',
            field=models.CharField(blank=True),
        ),
    ]
