# Generated by Django 5.0.3 on 2024-03-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0003_remove_business_description_alter_business_brn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/business_images/'),
        ),
    ]
