# Generated by Django 5.0.3 on 2024-03-25 07:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0004_alter_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='primaryColor',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='business',
            name='secondaryColor',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
    ]
