# Generated by Django 5.0.3 on 2024-03-25 08:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0005_business_primarycolor_business_secondarycolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='utmSource',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='primaryColor',
            field=colorfield.fields.ColorField(default='#034157', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='business',
            name='secondaryColor',
            field=colorfield.fields.ColorField(default='#097993', image_field=None, max_length=25, samples=None),
        ),
    ]
