# Generated by Django 4.2.6 on 2023-11-23 17:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('mobile_1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mobile_2', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nic_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance', models.CharField(choices=[('Swan', 'Swan'), ('Mauritius Union', 'Mauritius Union')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LensDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], max_length=5)),
                ('sph', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('axis', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_eye_test', models.CharField(blank=True, max_length=255)),
                ('care_system', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=255)),
                ('recommendation', models.TextField(blank=True)),
                ('next_checkup', models.DateField(blank=True, null=True)),
                ('vision', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlassPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_lenses', models.CharField(blank=True, max_length=255)),
                ('pdr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pdl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lens_detail_left', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_glass_prescription', to='dashboard.lensdetails')),
                ('lens_detail_right', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_glass_prescription', to='dashboard.lensdetails')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glass_prescription', to='dashboard.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLensPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_detail_left', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_contact_prescription', to='dashboard.lensdetails')),
                ('lens_detail_right', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_contact_prescription', to='dashboard.lensdetails')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lens_prescription', to='dashboard.prescription')),
            ],
        ),
    ]
