# Generated by Django 4.2.7 on 2023-11-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer_created_date_customer_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateField(default='2023-11-28'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateField(default='2023-11-28'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_date',
            field=models.DateField(default='2023-11-28'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='last_modified_date',
            field=models.DateField(default='2023-11-28'),
        ),
    ]
