# Generated by Django 4.2.7 on 2024-01-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateField(default='2024-01-11'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateField(default='2024-01-11'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_date',
            field=models.DateField(default='2024-01-11'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='last_modified_date',
            field=models.DateField(default='2024-01-11'),
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('contact_lenses', 'Contact Lenses'), ('lenses', 'Lenses')], max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('salesman', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_boxes', models.IntegerField(blank=True, null=True)),
                ('contact_lens', models.CharField(blank=True, max_length=100, null=True)),
                ('lens', models.CharField(blank=True, max_length=100, null=True)),
                ('base_curve', models.CharField(blank=True, max_length=100, null=True)),
                ('diameter', models.CharField(blank=True, max_length=100, null=True)),
                ('ht', models.CharField(blank=True, max_length=100, null=True)),
                ('frame', models.CharField(blank=True, max_length=100, null=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='dashboard.prescription')),
            ],
        ),
    ]
