# Generated by Django 4.2.7 on 2024-01-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='no_of_boxes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='supplier_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
