# Generated by Django 4.2.7 on 2024-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='created_date',
            field=models.DateField(default='2024-01-15'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='last_modified_date',
            field=models.DateField(default='2024-01-15'),
        ),
    ]
