# Generated by Django 4.2.7 on 2024-01-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_jobcard_created_date_jobcard_last_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
