# Generated by Django 4.2.7 on 2024-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='insurance',
            field=models.CharField(blank=True, choices=[('Swan', 'Swan'), ('Mauritius Union', 'Mauritius Union')], max_length=50, null=True),
        ),
    ]
