# Generated by Django 4.2.7 on 2024-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassprescription',
            name='pdl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='glassprescription',
            name='pdr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='glassprescription',
            name='type_of_lenses',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
