# Generated by Django 4.2.7 on 2024-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_glassprescription_pdl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlensprescription',
            name='contact_lens_add',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glassprescription',
            name='glass_add',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
