# Generated by Django 4.2.7 on 2024-01-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='estimated_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
