# Generated by Django 4.2.7 on 2024-01-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='number_of_patients',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
