# Generated by Django 4.2.7 on 2024-01-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_appointment_number_of_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='number_of_patients',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
