# Generated by Django 4.2.7 on 2024-01-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateField(default='2024-01-23'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateField(default='2024-01-23'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_date',
            field=models.DateField(default='2024-01-23'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='last_modified_date',
            field=models.DateField(default='2024-01-23'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_date',
            field=models.DateField(default='2024-01-23'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='last_modified_date',
            field=models.DateField(default='2024-01-23'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_purchase', models.DateField()),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('serial_number_or_barcode', models.CharField(blank=True, max_length=200, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.location')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.supplier')),
            ],
        ),
    ]
