# Generated by Django 4.2.7 on 2024-01-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_invoice_alter_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
