# Generated by Django 4.2.7 on 2024-01-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_invoicelineitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_issuer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateField(default='2024-01-31'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateField(default='2024-01-31'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_date',
            field=models.DateField(default='2024-01-31'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='last_modified_date',
            field=models.DateField(default='2024-01-31'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_date',
            field=models.DateField(default='2024-01-31'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='last_modified_date',
            field=models.DateField(default='2024-01-31'),
        ),
    ]
