# Generated by Django 4.2.7 on 2024-02-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_prescription_prescription_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateField(default='2024-02-01'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateField(default='2024-02-01'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_date',
            field=models.DateField(default='2024-02-01'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='last_modified_date',
            field=models.DateField(default='2024-02-01'),
        ),
        migrations.AlterField(
            model_name='location',
            name='storage_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_date',
            field=models.DateField(default='2024-02-01'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='last_modified_date',
            field=models.DateField(default='2024-02-01'),
        ),
    ]
