# Generated by Django 4.2.7 on 2024-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_jobcard_number_of_boxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateField(default='2024-02-02'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateField(default='2024-02-02'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_date',
            field=models.DateField(default='2024-02-02'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='last_modified_date',
            field=models.DateField(default='2024-02-02'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_date',
            field=models.DateField(default='2024-02-02'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='last_modified_date',
            field=models.DateField(default='2024-02-02'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
