# Generated by Django 4.2.7 on 2024-02-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='last_modified_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='last_modified_date',
            field=models.DateField(blank=True),
        ),
    ]
